server:
  port: 8080

spring:
  application:
    name: user-service

  spring:
    datasource:
      url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecommerce}
      username: ${SPRING_DATASOURCE_USERNAME:admin}
      password: ${SPRING_DATASOURCE_PASSWORD:password}
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
      properties:
        hibernate:
          default_schema: user

  jwt:
    secret: ${JWT_SECRET:dev_secret_key}

#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: user-service-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.devsocket.ecommerce.userservice: DEBUG